export const REMOVE_APP_STATES = 'REMOVE_APP_STATES';

//route
export const NAVIGATE_TO = 'NAVIGATE_TO';

//Apply-US
export const APPLY_US_SET_INITIAL_STATE = 'APPLY_US_SET_INITIAL_STATE';
export const APPLY_US_SET_VALUE = 'APPLY_US_SET_VALUE';
export const APPLY_US_SET_CURRENT_QUESTION = 'APPLY_US_SET_CURRENT_QUESTION';
export const APPLY_US_SET_ANSWERS = 'APPLY_US_SET_ANSWERS';
export const APPLY_US_CHANGE_HANDLER = 'APPLY_US_CHANGE_HANDLER';
export const APPLY_US_BACK_BUTTON_HANDLER = 'APPLY_US_BACK_BUTTON_HANDLER';
export const APPLY_US_NEXT_BUTTON_HANDLER = 'APPLY_US_NEXT_BUTTON_HANDLER';

//Pricing
export const PRICING_SET_INITIAL_STATE = 'PRICING_SET_INITIAL_STATE';
export const PRICING_SET_VALUE = 'PRICING_SET_VALUE';
export const PRICING_SET_CURRENT_QUESTION = 'PRICING_SET_CURRENT_QUESTION';
export const PRICING_SET_ANSWERS = 'PRICING_SET_ANSWERS';
export const PRICING_CHANGE_HANDLER = 'PRICING_CHANGE_HANDLER';
export const PRICING_BACK_BUTTON_HANDLER = 'PRICING_BACK_BUTTON_HANDLER';
export const PRICING_NEXT_BUTTON_HANDLER = 'PRICING_NEXT_BUTTON_HANDLER';