export const REMOVE_APP_STATES = 'REMOVE_APP_STATES';

//route
export const NAVIGATE_TO = 'NAVIGATE_TO';

//Apply-US
export const APPLY_US_SET_INITIAL_STATE = 'APPLY_US_SET_INITIAL_STATE';
export const APPLY_US_SET_VALUE = 'APPLY_US_SET_VALUE';
export const APPLY_US_SET_CURRENT_QUESTION = 'APPLY_US_SET_CURRENT_QUESTION';
export const APPLY_US_SET_ANSWERS = 'APPLY_US_SET_ANSWERS';
export const APPLY_US_CHANGE_HANDLER = 'APPLY_US_CHANGE_HANDLER';
export const APPLY_US_BACK_BUTTON_HANDLER = 'APPLY_US_BACK_BUTTON_HANDLER';
export const APPLY_US_NEXT_BUTTON_HANDLER = 'APPLY_US_NEXT_BUTTON_HANDLER';

//Start-a-project
export const START_PROJECT_SET_INITIAL_STATE = 'START_PROJECT_SET_INITIAL_STATE';
export const START_PROJECT_SET_VALUE = 'START_PROJECT_SET_VALUE';
export const START_PROJECT_SET_CURRENT_QUESTION = 'START_PROJECT_SET_CURRENT_QUESTION';
export const START_PROJECT_SET_ANSWERS = 'START_PROJECT_SET_ANSWERS';
export const START_PROJECT_CHANGE_HANDLER = 'START_PROJECT_CHANGE_HANDLER';
export const START_PROJECT_BACK_BUTTON_HANDLER = 'START_PROJECT_BACK_BUTTON_HANDLER';
export const START_PROJECT_NEXT_BUTTON_HANDLER = 'START_PROJECT_NEXT_BUTTON_HANDLER';